export type Lang = "en" | "sv";

export const COPY = {
  en: {
    navIndex: "Price index",
    navCheck: "Check an ask",
    footerLine: "Netfold shows what you keep, not what you should ask.",
    terms: "Terms",
    privacy: "Privacy",
    refunds: "Refunds",
    contact: "Contact",
    machine: "Machine",
    homeKicker: "What you actually keep",
    homeTitle: "See what you actually keep.",
    homeLead:
      "The ask lies. Fees, no-shows and instant buyers take the rest. Netfold scores net per channel — Blocket, Vinted, eBay — before you sell.",
    step1t: "Name or photo",
    step1d: "Identify the item. Condition included.",
    step2t: "Net per channel",
    step2d: "Local, Blocket, Vinted, eBay, instant.",
    step3t: "Unlock the report",
    step3d: "Pay once. Keep the link.",
    priceIndex: "Price index",
    allItems: "All items",
    sellThis: "Sell this",
    checkAsk: "Check an ask",
    priceIt: "Price it",
    photo: "Photo",
    try: "Try",
    counting: "Pricing…",
    askingPh: "Ask €",
    condLikeNew: "Like new",
    condGood: "Good",
    condFair: "Fair",
    condPoor: "Worn",
    errPrice: "Could not price that.",
    errMiss: "No match.",
    errPhoto: "Could not read that photo.",
    cookie:
      "We use cookies so checkout works. Payment cannot run until you press OK.",
    cookieMore: "Read more",
    cookieNo: "Decline",
    cookieOk: "OK",
    checkKicker: "Buy mode",
    checkTitle: "Is the ask sane?",
    checkLead:
      "Enter the item and what they want. Netfold compares that with what a seller actually keeps on honest channels.",
    marketKicker: "Price index",
    marketTitle: "What used gear actually puts in your pocket",
    marketLead: "Net ranges in good condition. Not asking prices. Each row is a page you can share.",
    itemMissing: "Not in the index yet",
    itemMissingLead: "Run a scan — that is how new models enter.",
    itemLead: "Used, good condition, take-home after fees — not the fantasy ask.",
    itemBest: "Best net is usually",
    itemInstant: "Instant buyers leave about",
    itemOnTable: "on the table.",
    likeNew: "Like new",
    fair: "Fair",
    brand: "Brand",
    priceYours: "Price yours",
    priceYoursLead: "Exact numbers per condition and listing copy sit behind the unlock.",
    backIndex: "Back to index",
    scanMissing: "Scan not found",
    scanMissingLead: "The link is invalid or expired.",
    modeBuy: "Check ask",
    modeSell: "What you keep",
    items: "items",
    bestNet: "best net on",
    instantLeaves: "instant leaves",
    onTable: "on the table",
    aLot: "a lot",
    chLocal: "Local",
    chFacebook: "Marketplace",
    chVinted: "Vinted",
    chEbay: "eBay",
    chInstant: "Instant",
    unlockNet: "Unlock the net",
    unlockLead: "Exact amounts, ranked channels, ask and accept. Listing copy is the kit.",
    skuReport: "Unlock report",
    skuExtract: "Extract kit",
    skuPack: "5-pack",
    payFineprint: "Digital report. Instant. Stripe takes the card. Save the link — that is the receipt.",
    cookieFirst: "Accept cookies first (OK at the bottom) so payment works.",
    cookieNeed: "Accept cookies first.",
    checkoutFail: "Checkout failed.",
    unlockedCredit: "Unlocked with a pack credit.",
    ask: "Ask",
    accept: "Accept",
    walk: "Walk",
    extractTitle: "Extract",
    extractLead: "Send the link. Copy the listing. Keep the net.",
    copied: "Copied",
    shareFigure: "Share this number",
    openIndex: "Open in price index",
    copyListing: "Copy listing",
    copyLowball: "Copy lowball reply",
    reportUnlocked: "Report unlocked. Add the kit if you want listing copy.",
    shareLine: "I actually keep",
    for: "for",
    via: "via Netfold.",
    paidWorking: "Confirming payment",
    paidOk: "Unlocked",
    paidFail: "Payment was not confirmed",
    paidWorkingLead: "We are attaching the receipt to the report.",
    paidOkLead: "The report is open. Save the link.",
    paidFailLead: "If you were charged, the webhook will unlock the scan. Refresh in a moment.",
    openReport: "Open the report",
    termsTitle: "Terms",
    terms1:
      "Netfold is software that estimates used-goods take-home value and sells digital reports and listing kits. We are not a marketplace, broker, pawn shop, or buyer of your items. We do not take possession of goods and we do not hold buyer funds.",
    terms2:
      "Estimates use a public catalog, published marketplace fee schedules, and (when you upload a photo) an identification model. They are not appraisals, guarantees, or offers to purchase. Sold prices move. Condition is a guess.",
    terms3:
      "Payment is charged by Stripe. You receive a digital unlock against the scan token. Chargebacks may reverse the unlock. Do not upload photos of other people, illegal goods, or anything you do not have the right to process.",
    terms4: "Swedish and EU consumer rules apply where they must. Governing law: Sweden.",
    privacyTitle: "Privacy",
    privacy1:
      "Netfold collects as little as possible. Without an account, only a random wallet token lives in the browser. We do not sell data.",
    privacy2:
      "Cookies: netfold_consent remembers your choice. Stripe checkout cannot run until you press OK. Card numbers are not stored with us.",
    privacy3:
      "Photos are sent to xAI for identification and then discarded. Do not photograph faces, ID documents, or anything you do not want processed.",
    privacy4:
      "Stripe receives what it needs for payment. Their privacy policy covers that transaction.",
    refundTitle: "Refunds",
    refund1:
      "Reports and extract kits are digital and delivered immediately. If the unlock did not appear, open the original scan link or contact us from the receipt — we will restore access. That is a fulfilment repair, not a quality dispute.",
    refund2:
      "Numbers are visible the moment you pay. We do not refund simply because you disagree with a price. If identification is obviously wrong (the model is not the item), ask for a refund within 24 hours and include the scan link.",
    refund3:
      "EU withdrawal rights for digital content end when delivery starts, after you are told that.",
    contactTitle: "Contact",
    contact1:
      "Netfold is automated. Payment issues go through the Stripe receipt. Product issues: reopen your scan link. If access did not unlock after a successful payment, keep the receipt — fulfilment is keyed to the Stripe session.",
    contact2: "Legal notices: the operator is the GitHub account that publishes jonjys/netfold.",
    contact3: "There is no chat queue. That is the point.",
  },
  sv: {
    navIndex: "Prisindex",
    navCheck: "Kolla en ask",
    footerLine: "Netfold visar vad du får kvar, inte vad du ska be om.",
    terms: "Villkor",
    privacy: "Integritet",
    refunds: "Återköp",
    contact: "Kontakt",
    machine: "Maskin",
    homeKicker: "Vad du får i fickan",
    homeTitle: "Se vad du faktiskt får kvar.",
    homeLead:
      "Utropet ljuger. Avgifter, no-shows och instant-köpare tar resten. Netfold räknar nettot per kanal — Blocket, Vinted, eBay — innan du säljer.",
    step1t: "Namn eller foto",
    step1d: "Identifiera prylen. Skick ingår.",
    step2t: "Netto per kanal",
    step2d: "Lokalt, Blocket, Vinted, eBay, instant.",
    step3t: "Lås upp rapporten",
    step3d: "Betala en gång. Spara länken.",
    priceIndex: "Prisindex",
    allItems: "Alla prylar",
    sellThis: "Sälj detta",
    checkAsk: "Kolla en ask",
    priceIt: "Prissätt",
    photo: "Foto",
    try: "Prova",
    counting: "Räknar…",
    askingPh: "Utrop €",
    condLikeNew: "Som ny",
    condGood: "Bra",
    condFair: "Okej",
    condPoor: "Sliten",
    errPrice: "Kunde inte prissätta.",
    errMiss: "Ingen träff.",
    errPhoto: "Foto gick inte att läsa.",
    cookie:
      "Vi använder cookies så att betalningen fungerar. Checkout körs inte förrän du trycker OK.",
    cookieMore: "Läs mer",
    cookieNo: "Avböj",
    cookieOk: "OK",
    checkKicker: "Köpläge",
    checkTitle: "Är utropet vettigt?",
    checkLead:
      "Skriv prylen och vad de vill ha. Netfold jämför med vad en säljare faktiskt får kvar på de ärliga kanalerna.",
    marketKicker: "Prisindex",
    marketTitle: "Vad begagnat faktiskt ger i fickan",
    marketLead: "Nettospann i bra skick. Inte utropspriser. Varje rad är en sida du kan dela.",
    itemMissing: "Inte i indexet än",
    itemMissingLead: "Kör en scan — så kommer nya modeller in.",
    itemLead: "Begagnat, bra skick, netto efter avgifter — inte utropsfantasin.",
    itemBest: "Bästa nettot brukar vara",
    itemInstant: "Instant-köpare lämnar ungefär",
    itemOnTable: "på bordet.",
    likeNew: "Som ny",
    fair: "Okej skick",
    brand: "Märke",
    priceYours: "Prissätt din",
    priceYoursLead: "Exakta tal per skick och annonstext ligger bakom upplåsningen.",
    backIndex: "Tillbaka till index",
    scanMissing: "Scanen hittades inte",
    scanMissingLead: "Länken är ogiltig eller har gått ut.",
    modeBuy: "Kolla ask",
    modeSell: "Vad du får kvar",
    items: "prylar",
    bestNet: "bäst netto på",
    instantLeaves: "instant lämnar",
    onTable: "på bordet",
    aLot: "en hel del",
    chLocal: "Lokalt",
    chFacebook: "Marketplace",
    chVinted: "Vinted",
    chEbay: "eBay",
    chInstant: "Direkt",
    unlockNet: "Lås upp nettot",
    unlockLead: "Exakta belopp, rankade kanaler, ask och accept. Annonstexten är kitet.",
    skuReport: "Lås upp rapport",
    skuExtract: "Extract-kit",
    skuPack: "5-pack",
    payFineprint: "Digital rapport. Direkt. Stripe tar kortet. Spara länken — det är kvittot.",
    cookieFirst: "Godkänn cookies först (OK längst ner) så betalningen fungerar.",
    cookieNeed: "Godkänn cookies först.",
    checkoutFail: "Checkout misslyckades.",
    unlockedCredit: "Upplåst med ett pack-kredit.",
    ask: "Utrop",
    accept: "Acceptera",
    walk: "Gå",
    extractTitle: "Utdrag",
    extractLead: "Skicka länken. Kopiera annonsen. Behåll nettot.",
    copied: "Kopierat",
    shareFigure: "Dela den här siffran",
    openIndex: "Öppna i prisindex",
    copyListing: "Kopiera annons",
    copyLowball: "Kopiera lowball-svar",
    reportUnlocked: "Rapporten är upplåst. Lägg till kitet om du vill ha annonstext.",
    shareLine: "Jag får faktiskt",
    for: "för",
    via: "via Netfold.",
    paidWorking: "Bekräftar betalning",
    paidOk: "Upplåst",
    paidFail: "Betalningen bekräftades inte",
    paidWorkingLead: "Vi lägger kvittot i rapporten.",
    paidOkLead: "Rapporten är öppen. Spara länken.",
    paidFailLead: "Om du debiterades låser webhooken upp scannen. Uppdatera om en stund.",
    openReport: "Öppna rapporten",
    termsTitle: "Villkor",
    terms1:
      "Netfold är programvara som uppskattar vad du får kvar när du säljer begagnat, och säljer digitala rapporter och annonskit. Vi är inte en marknadsplats, mäklare, pantbank eller köpare av dina prylar. Vi tar inte hand om varor och vi håller inte köparens pengar.",
    terms2:
      "Uppskattningarna bygger på en katalog, publicerade avgifter och (om du laddar upp foto) en identifieringsmodell. Det är inte värderingar, garantier eller bud. Sålda priser rör sig. Skick är en gissning.",
    terms3:
      "Betalning tas av Stripe. Du får en digital upplåsning mot scan-token. Chargeback kan låsa igen. Ladda inte upp foton på andra personer, olagliga varor eller något du inte har rätt att behandla.",
    terms4: "Svensk och EU-konsumenträtt gäller där den måste. Tillämplig lag: Sverige.",
    privacyTitle: "Integritet",
    privacy1:
      "Netfold samlar in så lite som möjligt. Utan konto ligger bara en slumpmässig plånbokstoken i webbläsaren. Vi säljer ingen data.",
    privacy2:
      "Cookies: netfold_consent minns ditt val. Stripe-checkout körs inte förrän du trycker OK. Kortnummer lagras inte hos oss.",
    privacy3:
      "Foton skickas till xAI för identifiering och kastas sedan. Fotografera inte ansikten, id-handlingar eller något du inte vill ska behandlas.",
    privacy4:
      "Stripe tar emot det de behöver för betalning. Deras integritetspolicy gäller den transaktionen.",
    refundTitle: "Återköp",
    refund1:
      "Rapporter och extract-kit är digitala och levereras direkt. Om upplåsningen inte syns: öppna samma scan-länk eller kontakta oss via kvittot — då återställer vi åtkomsten. Det är en leveransreparation, inte en kvalitetsreklamation.",
    refund2:
      "Siffrorna syns i samma ögonblick du betalar. Vi återbetalar inte bara för att du tycker att priset är fel. Om identifieringen uppenbart är fel (fel modell) kan du begära återköp inom 24 timmar och skicka med scan-länken.",
    refund3:
      "Ångerrätten för digitalt innehåll i EU upphör när leveransen börjar, efter att du informerats om det.",
    contactTitle: "Kontakt",
    contact1:
      "Netfold är automatiserat. Betalningsfrågor går via Stripe-kvittot. Produktfrågor: öppna din scan-länk. Om åtkomsten inte låstes upp efter lyckad betalning — spara kvittot. Leveransen är knuten till Stripe-sessionen.",
    contact2: "Juridiska meddelanden: operatören är GitHub-kontot som publicerar jonjys/netfold.",
    contact3: "Det finns ingen chattkö. Det är poängen.",
  },
} as const;

export type CopyKey = keyof typeof COPY.en;
